<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Users Report PDF</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #222;
            font-size: 12px;
            margin-bottom: 60px;

        }

        .header {
            width: 100%;
            border-bottom: 2px solid #d9d9d9;
            padding-bottom: 12px;
            margin-bottom: 20px;
        }

        .header-table {
            width: 100%;
            border-collapse: collapse;
        }

        .header-table td {
            vertical-align: middle;
            border: none;
        }

        .logo-cell {
            width: 90px;
        }

        .logo {
            width: 70px;
            height: 70px;
            object-fit: contain;
        }

        .title-main {
            font-size: 26px;
            font-weight: bold;
            color: #c1121f;
            margin: 0;
        }

        .title-sub {
            font-size: 14px;
            margin-top: 4px;
            color: #444;
        }

        .report-title {
            text-align: center;
            font-size: 20px;
            font-weight: bold;
            margin-top: 20px;
            margin-bottom: 8px;
        }

        .report-date {
            text-align: center;
            font-size: 12px;
            margin-bottom: 20px;
        }

        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        .data-table th,
        .data-table td {
            border: 1px solid #cfcfcf;
            padding: 8px;
            font-size: 11px;
        }

        .data-table th {
            background-color: #d71920;
            color: #ffffff;
            text-align: center;
        }

        .text-center {
            text-align: center;
        }
        .footer {
            position: fixed;
            bottom: 20px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 12px;
            color: #555;
        }
    </style>
</head>
<body>
<div class="footer">
    Generated by Admin
</div>
    <div class="header">
        <table class="header-table">
            <tr>
                <td class="logo-cell">
                    <img src="{{ public_path('assets/img/bloodconnect-logo.png') }}" class="logo" alt="BloodConnect Logo">
                </td>
                <td>
                    <div class="title-main">BLOODCONNECT</div>
                    <div class="title-sub">AI-Powered Blood Donation and Matching Platform</div>
                </td>
            </tr>
        </table>
    </div>

    <div class="report-title">Users Report</div>
    <div class="report-date">Date Generated: {{ date('F d, Y') }}</div>
    

    <table class="data-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Birth Date</th>
                <th>Gender</th>
                <th>Phone Number</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($users as $user)
                <tr>
                    <td class="text-center">{{ $user->id }}</td>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td class="text-center">{{ $user->role->value }}</td>
                    <td class="text-center">{{ $user->birth_date }}</td>
                    <td class="text-center">{{ $user->gender }}</td>
                    <td class="text-center">{{ $user->phone }}</td>
                    <td class="text-center">{{ $user->status }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" class="text-center">No records found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

</body>
</html>